### PR TITLE
[REEF-1763] Replace interop call to StartHandlerOnNext()

### PR DESCRIPTION
**Pull request by dougmsft**
* This changes starts the process of splitting the bridge
    into two separate executables, one Java and one C#,
    connected via an Avro messaging protocol.
  * Adds a protocol serializer and remote manager to
    both sides of the bridge which implement serializing
    and deserializing bridge Avro messages and provides
    the byte level network transport.
  * Replaces the SystemOnStart interop call with a
    SystemOnStart Avro message from Java to C# with
    an ack back to the Java side.

JIRA:
  [REEF-1763] (https://issues.apache.org/fira/browse/REEF-1763)

Pull request:
  This closes #

### CODE REVIEW

**Review by motus — CHANGES_REQUESTED** [review]
For starters: unit tests fail due to Checkstyle violation:
```text
[ERROR] src/main/java/org/apache/reef/bridge/JavaBridge.java:[32,8] (imports) UnusedImports: Unused import - java.util.concurrent.Executors.
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (validate) on project reef-bridge-java: You have 1 Checkstyle violation. -> [Help 1]
```

**Comment by motus** [comment]
Also: let's not merge that commit into master yet. Instead, create another branch, say, REEF-Bridge (or use some appropriate JIRA ID), which originally will be just a copy of master, and then create a pull request from branch REEF-1763 into that bridge branch. Both bridge branch and REEF-1763 can reside on your private repo on github. This way, the bridge branch in your repo will accumulate all reviewed PRs for individual bridge calls.

**Comment by dougmsft** [comment]
I did run the test multiple times but this was a late change.

Also, I have created a branch REEF-335 which is the number of the parent.

**Comment by dougmsft** [comment]
Fixed issues and with pull against REEF-335

**Pull request closed without merging**
